module.exports = {
    "type":"object",
    "required":[
        "components",
        "externalPorts",
        "composeFile",
        "environmentalVariables"
    ],
    "properties":{
        "components":{
            "type":"object",
            "patternProperties":{
                "^[_a-zA-Z\\d]+$":{
                    "required":[
                        "source",
                        "reference",
                        "beforeBuildTasks"
                    ],
                    "properties":{
                        "source":{
                            "type":"object",
                            "required":[
                                "type"
                            ],
                            "properties":{
                                "type":{
                                    "type":"string",
                                    "minLegth":1
                                }
                            }
                        },
                        "reference":{
                            "type":"object",
                            "required":[
                                "type",
                                "name"
                            ],
                            "properties":{
                                "type":{
                                    "type":"string",
                                    "minLength":1
                                },
                                "name":{
                                    "type":"string",
                                    "minLength":1
                                }
                            }
                        },
                        "beforeBuildTasks":{
                            "type":"array",
                            "items":{
                                "type":"object",
                                "required":[
                                    "type"
                                ],
                                "properties":{
                                    "type":{
                                        "type":"string",
                                        "minLength":1
                                    }
                                }
                            }
                        },
                        "afterBuildScripts":{
                            "type":"array",
                            "items":{
                                "type":"string",
                                "minLength":1
                            }
                        }
                    }
                }
            },
            "additionalProperties":false
        },
        "externalPorts":{
            "type":"object",
            "patternProperties":{
                "^[_a-zA-Z\\d]+$":{
                    "type":"object",
                    "required":[
                        "ranges"
                    ],
                    "properties":{
                        "ranges":{
                            "type":"array",
                            "minItems":1,
                            "items":{
                                "type":"array",
                                "minItems":2,
                                "maxItems":2,
                                "items":[
                                    {
                                        "type":"number",
                                        "minimum":1
                                    },
                                    {
                                        "type":"number",
                                        "minimum":1
                                    }
                                ]
                            }
                        }
                    }
                }
            },
            "additionalProperties":false
        },
        "composeFile":{
            "type":"object",
            "required":[
                "componentId",
                "relativePath"
            ],
            "properties":{
                "componentId":{
                    "type":"string",
                    "minLength":1
                },
                "relativePath":{
                    "type":"string",
                    "minLength":1
                }
            }
        },
        "environmentalVariables":{
            "type":"object",
            "patternProperties":{
                "^(?!FEAT__)[A-Z\\d_]+$":{
                    "type":"string"
                }
            },
            "additionalProperties":false
        }
    }
};
